### ISSUE TITLE
LICENSE mismatch

### ISSUE THREAD

**Issue by DasBlackfur** [Mqxx/LCD-PS12032LRS-DGB-K01#5]
The license specified by you in the new "LICENSE" file (GPLv2) neither matches the one I originally specified in "LICENSE.md" (Apache 2.0), nor is it compatible.
While legally you are free to re license this codebase (due to the nature of the Apache 2.0 license), I would prefer if you kept the license as is and revert your commit.

**Comment by Mqxx** [comment]
The reason for the license change was due to commercial use. I want this project to be developed open source under the same license. The GLP v2.0 license ensures that.

> Copyleft vs. permissive: The GPL (General Public License) is a so-called "copyleft" license, which means that derived works must be published under the same license and the source code for these works must be available. The Apache 2.0 license, on the other hand, is more permissive. *It does not require derivative works to be published under the same license, nor is it necessary to disclose the source code for derivative works unless they are distributed as separate products.*

I have generally switched to the GLP v2.0 license for all my projects. In the beginning, I wasn't so clear about copyleft vs. permissive.

Please be understanding about this and adjust the license for yourself accordingly.

**Comment by Mqxx** [comment]
Also, this project was not really intended for production yet. The only reason for the publication were the data sheets, as these were very difficult to find.

**Comment by DasBlackfur** [comment]
While I understand your approach I would suggest the LGPLv3. This would enable the development of this library to be under strong copyleft terms while the pure use of this library remains relatively unrestricted.
Additionally you will have to add a notice that exempts the datasheets not created by you from any terms specified in the LICENSE file, since neither of us can claim any rights to those.

**Comment by Mqxx** [comment]
LGPLv3 does not enforce strong copyleft...

> The GPL is a strong copyleft license, which means that it forces applications that use it to publish their source code changes under the GPL as well. The LGPL, on the other hand, has a weaker copyleft section and allows libraries licensed under the LGPL to be embedded in proprietary software _without that software having to disclose its source code changes_.

> _"without that software having to disclose its source code changes"_

This is what I dont't want. I want the software to stay open source.

> Additionally you will have to add a notice that exempts the datasheets not created by you from any terms specified in the LICENSE file, since neither of us can claim any rights to those.

Thats right. I need to add a notice.

**Comment by Mqxx** [comment]
I could also just remove the original Powertip Datasheets and just link them. The only Problem would be if they are no longer accessable, then the link would be dead. In this case we could just use the webarchive.

**Comment by DasBlackfur** [comment]
I would keep the datasheets for exactly that reason, but do note that the datasheets are from 3 separate vendors.

Regarding the license for this code: I am unable to find anything of that meaning, all sources I find more or less state:

> There are two main cases to consider: using the library without modifications, or using a modified library. 
> 
>  1   Without modification, you can include the library and redistribute it as part of other software. Note that you must make a notice about libraries you used, and where to find their source code. You can do that in the "about" menu of your application or in a readme file if there is no user interface. In many software like Android or Spotify, you will usually find a "third-party software" section in the parameters, with a detailed list of libraries, their license, and links to their sources. 
> 
>   2  If you modify the library before integration/compilation, you can also include and redistribute your version in any other software with a notice. However, LGPLv3 states that you can only share modified versions of the libraries with the same license or GPLv3. This means that you must also give access to the sources of your version, and you must make it clear that your version is different.

Especially case 2 applies here. I still think this would be ideal, since any development of the library itself would be shared with the FOSS community while proprietary vendors are enabled to build their closed source applications with this library.

**Comment by Mqxx** [comment]
>  This means that you must also give access to the sources of your version, and you must make it clear that your version is different.

I am not sure about this part... I don't think that you need to open source it with the LGPL... With the GPL you must!

**Comment by DasBlackfur** [comment]
Every summary I find states it more or less like this:

> [The LGPL] license is mainly applied to libraries. You may copy, distribute and modify the software provided that modifications are described and licensed for free under LGPL. Derivatives works (including modifications or anything statically linked to the library) can only be redistributed under LGPL, but applications that use the library don't have to be.

And even digging through the convoluted license document itself, I don't see any clause in the LPGLv3 that would release you from the GLPv3 term to disclose source.

As stated already the GPL has the big disadvantage that pure use (without any modification) of the library is not permitted without disclosing the source of your application. (so long distribution is happening)

Of course you are free to choose whatever you want for your own libraries, but I would really prefer if this library was kept under a more permissive license.

**Comment by Mqxx** [comment]
Okay. I will change the license to `LGPL v2`. [Here you can read more about "Why not LGPL"](https://www.gnu.org/licenses/why-not-lgpl)

**Comment by DasBlackfur** [comment]
I am aware of that post. May I ask why v2 and not v3?

**Comment by Mqxx** [comment]
- **Patent licensing**: The GPLv3 contains patent licensing provisions to ensure that users of the software are not restricted by patents held by a contributor.
- **Tivoization**: The GPLv3 contains provisions designed to prevent hardware manufacturers from designing their devices to run proprietary software while restricting user freedoms. This is known as "Tivoization", named after TiVo's practice of running proprietary software on their devices and making it difficult for users to change it.
- **Digital Rights Management (DRM)**: GPLv3 prohibits the use of the software in conjunction with DRM mechanisms that could restrict the user's freedoms.
- **Compatibility**: Some have noted that the GPLv3 is less compatible with other licenses than the GPLv2, such as the Apache license, which is compatible with the GPLv2 but not necessarily with the GPLv3.
- **Internationalization**: The GPLv3 has been internationalized to ensure that it is effective in different jurisdictions.
Disclaimer: The GPLv3 contains a more comprehensive disclaimer than the GPLv2.

The version 2 is more compatible with other licenses than the version 3.

**Comment by DasBlackfur** [comment]
But wouldn't especially the part about "Tivoization" be reasonable in this case?
And compatibility doesn't really affect the LPGL.

**Comment by Mqxx** [comment]
I did not know there was a LGPLv3. I changed it to v3.

**Comment by DasBlackfur** [comment]
Great, now the copyright notice for the datasheets has to be expanded to the other 2 vendors.
And thank you.

**Comment by Mqxx** [comment]
> now the copyright notice for the datasheets has to be expanded to the other 2 vendors

Done.

**Comment by DasBlackfur** [comment]
Great, thanks for clearing this up!

**Comment by Mqxx** [comment]
No problem 👍
